/*
 * (C) Copyright 2018 Nuxeo (http://nuxeo.com/) and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *     Funsho David
 */

package org.nuxeo.ecm.annotation;

/**
 * External annotation interface.
 * 
 * @since 10.3
 */
public interface ExternalAnnotation {

    /**
     * Gets annotation entity id, generated by the external service.
     *
     * @return the entity id
     */
    String getEntityId();

    /**
     * Sets annotation entity id.
     *
     * @param entityId the entity id
     */
    void setEntityId(String entityId);

    /**
     * Gets annotation origin.
     * 
     * @return the origin
     */
    String getOrigin();

    /**
     * Sets annotation origin.
     * 
     * @param origin the origin
     */
    void setOrigin(String origin);

    /**
     * Gets annotation entity. This represents the annotation model as the rendition server describes it.
     *
     * @return the entity
     */
    String getEntity();

    /**
     * Sets annotation entity.
     *
     * @param entity the entity
     */
    void setEntity(String entity);

}
