# vim:set ft=dockerfile:
# Choose this slim Dockerfile to build a light image without conversion capability

# ------------------------------------------------------------------------
# Build Stage: Unzip the distribution
FROM alpine:3.10.2 as distrib

COPY target/nuxeo-server-tomcat-*.zip /tmp/nuxeo-distribution-tomcat.zip

RUN mkdir -p /tmp/nuxeo-distribution \
  && unzip -q -d /tmp/nuxeo-distribution /tmp/nuxeo-distribution-tomcat.zip \
  && DISTDIR=$(/bin/ls /tmp/nuxeo-distribution | head -n 1) \
  && mv /tmp/nuxeo-distribution/$DISTDIR /distrib \
  && sed -i -e "s/^org.nuxeo.distribution.package.*/org.nuxeo.distribution.package=docker/" /distrib/templates/common/config/distribution.properties \
  && rm -rf /tmp/nuxeo-distribution* \
  && chmod +x /distrib/bin/*ctl /distrib/bin/*.sh \
  && chmod -R g+rwX /distrib

COPY docker/docker-template /distrib/templates/docker


# ------------------------------------------------------------------------
# Build Stage: Base image with Java and no converter
FROM centos:7 as slim

RUN yum -y update && yum -y --setopt=skip_missing_names_on_install=False install \
  java-11-openjdk java-11-openjdk-devel \
  less \
  tar \
  unzip \
  wget \
  && yum clean all

# Remove setuid/setgid binaries from images for security
RUN find / -perm 6000 -type f -exec chmod a-s {} \; || true


# ------------------------------------------------------------------------
# Target Stage: Nuxeo image
FROM slim
LABEL maintainer="Nuxeo <packagers@nuxeo.com>"

# Add a nuxeo user
ENV NUXEO_USER nuxeo
RUN useradd -m -d /home/$NUXEO_USER -u 1000 -s /bin/bash $NUXEO_USER

# Copy distribution
ENV NUXEO_HOME /opt/nuxeo/server
COPY --from=distrib /distrib $NUXEO_HOME
# Work around missing support for --chown flag with COPY instruction in Kaniko
# TODO NXP-28052: remove and use COPY --chown when fixed in Kaniko, or find a proper way
RUN chown -R 1000:0 $NUXEO_HOME

COPY --chown=1000:0 docker/nuxeo.conf /etc/nuxeo/nuxeo.conf.template
COPY docker/docker-entrypoint.sh /

# Protecting writeable directories to support arbitrary User IDs for OpenShift
# https://docs.openshift.com/container-platform/3.4/creating_images/guidelines.html
RUN chown -R 1000:0 /etc/nuxeo && chmod g+rwX /etc/nuxeo && rm -f $NUXEO_HOME/bin/nuxeo.conf \
  && mkdir -p /var/lib/nuxeo/data \
  && chown -R 1000:0 /var/lib/nuxeo/data && chmod -R g+rwX /var/lib/nuxeo/data \
  && mkdir -p /var/log/nuxeo \
  && chown -R 1000:0 /var/log/nuxeo && chmod -R g+rwX /var/log/nuxeo \
  && mkdir -p /var/run/nuxeo \
  && chown -R 1000:0 /var/run/nuxeo && chmod -R g+rwX /var/run/nuxeo \
  && mkdir -p /docker-entrypoint-initnuxeo.d \
  && chown -R 1000:0 /docker-entrypoint-initnuxeo.d && chmod -R g+rwX /docker-entrypoint-initnuxeo.d  \
  && chmod g=u /etc/passwd

ENV NUXEO_CONF /etc/nuxeo/nuxeo.conf
ENV HOME $NUXEO_HOME
ENV PATH $NUXEO_HOME/bin:$PATH
WORKDIR $NUXEO_HOME
EXPOSE 8080
USER 1000
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nuxeoctl","console"]
