<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cloud.docbyte.nuxeo</groupId>
    <artifactId>nuxeo-ecm</artifactId>
    <version>2026.1-SNAPSHOT</version>
  </parent>

  <artifactId>boms</artifactId>
  <packaging>pom</packaging>
  <name>Nuxeo Boms</name>

  <modules>
    <module>nuxeo-opensearch1-bom</module>
  </modules>

</project>
