#!/bin/sh
APPDIR=`dirname $0`;
if [ "x$GWT_HOME" = "x" ] ; then
    echo GWT_HOME not defined
    exit 1;
fi

java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/target/www" "$@" org.nuxeo.ecm.platform.gwt.Core;
