version: 2
updates:
  # Default branch: 2023
  # Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Paris"
    # Limit version updates to 10 to prevent CI overload
    open-pull-requests-limit: 10
    # Group all version updates (patch only)
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
    ignore:
      # Major and minor version updates
      - dependency-name: "*"
        update-types: [
          "version-update:semver-major",
          "version-update:semver-minor"
        ]

      # Spurious major version updates
      - dependency-name: "com.google.apis:google-api-services-drive"
        versions: [">v2-rev20201130-1.31.0"]

      # Unwanted NX minor version update due to jakarta compatibility
      - dependency-name: "org.apache.commons:commons-dbcp2"
        versions: [">2.13"]

      # Patch version updates breaking compilation
      - dependency-name: "org.apache.directory.server:*"
        versions: [">1.5.1"]
      - dependency-name: "org.apache.directory.shared:*"
        versions: [">0.9.7"]
      - dependency-name: "io.dropwizard.metrics5:metrics-bom"
        versions: [">5.0.0-rc3"]

      # Patch version update not interesting
      - dependency-name: "org.apache.geronimo.components:geronimo-transaction"
        versions: [">3.1.4-NX1"]

      # Patch version containing regression
      - dependency-name: "org.quartz-scheduler:quartz"
        versions: ["2.5.1"]

      # Not in our artifact repository
      - dependency-name: "commons-httpclient:commons-httpclient"
        versions: [ ">3.1" ] # no update to 3.1-jenkins-x

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all version updates (major, minor and patch)
    groups:
      version-updates:
        applies-to: "version-updates"
        patterns:
          - "*"

  # Branch 2025
  # Maven
  - package-ecosystem: "maven"
    target-branch: "2025"
    directory: "/"
    schedule:
        interval: "daily"
        time: "01:00"
        timezone: "Europe/Paris"
    # Limit version updates to 10 to prevent CI overload
    open-pull-requests-limit: 10
    # Group all version updates (minor and patch)
    groups:
      version-updates:
        patterns:
          - "*"
    # Cooldown period for patch version updates, such as AWS SDK BOM released very frequently
    cooldown:
      semver-patch-days: 7
      include:
        - "software.amazon.awssdk:bom"
    ignore:
      # Major version updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

      # Spurious major version updates
      - dependency-name: "com.google.apis:google-api-services-drive"
        versions: [">v2-rev20201130-1.31.0"]
      - dependency-name: "net.oauth.core:oauth"
        versions: [">20090531"] # 20100527 is detected as more recent but is actually older

      # Jakarta EE minor updates
      - dependency-name: "jakarta.*:*"
        update-types: ["version-update:semver-minor"]

      # Pre-release version that is taking precedence over the regular one
      - dependency-name: "jakarta.inject:jakarta.inject-api"
        versions: ["2.0.1.MR"]

      # Minor version updates breaking compilation
      - dependency-name: "org.osgi:org.osgi.core"
        versions: ["[4.4,)"]
      - dependency-name: "io.gatling*:*"
        versions: ["[3.13.0,)"]

      # Minor version updates breaking tests
      - dependency-name: "org.hibernate.orm:hibernate-core"
        versions: [">=6.6.0.Final"] # with this minor update, audit can't append entity with manually set id

      # Patch version updates breaking compilation
      - dependency-name: "org.apache.directory.server:*"
        versions: [">1.5.1"]
      - dependency-name: "org.apache.directory.shared:*"
        versions: [">0.9.7"]

      # Patch version containing regression
      - dependency-name: "org.quartz-scheduler:quartz"
        versions: ["2.5.1"]

      # Nuxeo patch needed
      - dependency-name: "com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer"
        versions: [">20211018.2.NX1"]

      # Not in our artifact repository
      - dependency-name: "commons-httpclient:commons-httpclient"
        versions: [ ">3.1" ] # no update to 3.1-jenkins-x
      - dependency-name: "org.glassfish.web:jakarta.servlet.jsp.jstl"
        versions: [ ">3.0.1" ] # no update to 3.0.1-jbossorg-1
      - dependency-name: "org.codehaus.mojo:license-maven-plugin"
        versions: ["[1.20, 1.21)"] # no update to 1.20.jbossorg-3

      # Prometheus simpleclient 0.12 contains breaking change
      - dependency-name: "io.prometheus:simpleclient*"
        versions: [">0.11"]

      # NXP-33565: Confluent patch release breaking build
      - dependency-name: "io.confluent:*"
        versions: ["7.9.6"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "2025"
    directory: "/"
    schedule:
      interval: "daily"
    # Group all version updates (major, minor and patch)
    groups:
      version-updates:
        patterns:
          - "*"
