dependencies:
- name: mongodb
  version: 4.1.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mongodb
- name: postgresql
  version: 3.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nuxeo.postgresql.deploy
  alias: postgresql  
