image:
  tag: "13.0.0"
initdbScripts:
  db-init.sql: |
    CREATE ROLE nuxeo WITH PASSWORD 'nuxeo' LOGIN;
    CREATE DATABASE nuxeo ENCODING 'UTF8' OWNER nuxeo;
persistence:
  enabled: $PERSISTENCE
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"
master:
  labels:
    branch: "$BRANCH_NAME"
    resource: statefulset
    team: platform
    usage: "$USAGE"
  podLabels:
    branch: "$BRANCH_NAME"
    resource: pod
    team: platform
    usage: "$USAGE"
  tolerations:
    - key: team
      operator: Equal
      value: platform
      effect: NoSchedule
  nodeSelector:
    team: platform
