version: 0.2
env:
  variables:
    CHANGELIST: "-SNAPSHOT"
    AWS_ACCOUNT_ID: "518241560725"

phases:

  install:
    runtime-versions:
      java: corretto21
    commands:
      - yum -y install glibc-all-langpacks
      - export LC_ALL="en_US.UTF-8"
      - export LANG="en_US.UTF-8"
      - java -version
      - yum -y upgrade
      - java -version
      - aws s3 sync s3://dev.tools.s3.devops.docbyte.cloud/ ~/tools/
      - chmod a+x -R ~/tools/
      - . ~/tools/prepEnv.sh
      - . ~/tools/codebuild-gittools.sh
      - echo Build Started
      - . ci/codebuild/installRequirements.sh
      - . ci/codebuild/setupTestEnv.sh
  pre_build:
    commands:
      - REGISTRY_URI=518241560725.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=518241560725.dkr.ecr.eu-west-1.amazonaws.com/docbyte-nuxeo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - . ~/tools/codebuild-versioning.sh
      - IMAGE_TAG=${VERSION:=latest}
      - MAVEN_ARGS=" -Prelease,distrib,docker,kafka -nsu -ntp -Djdk.util.zip.disableZip64ExtraFieldValidation=true -Dnuxeo.skip.enforcer=true -Dcustom.environment=mongodb -Dcustom.environment.log.dir=target-mongodb -Dnuxeo.test.core=mongodb -Dnuxeo.test.redis.host=localhost -Pkafka -Dkafka.bootstrap.servers=localhost:9092 -Ddocker.verbose=true"
      - mvn versions:set -DnewVersion=${VERSION} -DgenerateBackupPoms=false $MAVEN_ARGS
      - sed -i -E "s/<nuxeo.platform.version>.*?<\/nuxeo.platform.version>/<nuxeo.platform.version>$VERSION<\/nuxeo.platform.version>/" pom.xml
      - sed -i -E "s/<version>\\$\{nuxeo.platform.version\}<\/version>/<version>$VERSION<\/version>/" pom.xml
      - sed -i -E "s/org.nuxeo.ecm.product.version=.*/org.nuxeo.ecm.product.version=$VERSION/" server/nuxeo-nxr-server/src/main/resources/templates/nuxeo.defaults
      - sed -i -E "s/<version>.*?<\/version>/<version>$VERSION<\/version>/" parent/pom.xml


  build:
    commands:
      - LANG=en_US.utf8 mvn -pl "!cloud.docbyte.nuxeo.docker:nuxeo-benchmark-docker-image" clean deploy $MAVEN_ARGS -fae
      - mvn -DskipTests=true $MAVEN_ARGS -f parent/pom.xml deploy
      - docker tag nuxeo/nuxeo:2025.x $REPOSITORY_URI:latest
      - docker tag nuxeo/nuxeo:2025.x $REPOSITORY_URI:$IMAGE_TAG
      - echo Build finished on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Deployment done `date`
    finally:
      - docker images
reports:
  SurefireReports:
    files:
      - 'target-mongodb/surefire-reports/**/*'
      - '**/target-mongodb/surefire-reports/**/*'
