<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.nuxeo.ecm</groupId>
    <artifactId>nuxeo-drive-parent</artifactId>
    <version>2025.20-SNAPSHOT</version>
  </parent>

  <groupId>org.nuxeo.ecm</groupId>
  <artifactId>nuxeo-drive-elasticsearch</artifactId>
  <name>Nuxeo Drive Elasticsearch</name>
  <description>Nuxeo Drive Elasticsearch</description>

  <dependencies>
    <!-- Java specifications -->

    <!-- Libraries -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>

    <!-- Nuxeo dependencies -->
    <dependency>
      <groupId>org.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-search</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-search-client-opensearch1</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-features</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm</groupId>
      <artifactId>nuxeo-drive-core</artifactId>
    </dependency>

    <!-- Test libraries -->
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Nuxeo test libraries -->
    <dependency>
      <groupId>org.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-jtajca</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-event</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-core</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-io</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-server</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm</groupId>
      <artifactId>nuxeo-drive-core</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-audit-test</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-collections-core</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-filemanager</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-test</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-webapp-types</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-search-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.ecm.webengine</groupId>
      <artifactId>nuxeo-webengine-core</artifactId>
      <type>test-jar</type>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <archive>
                <manifestFile>src/test/resources/META-INF/MANIFEST.MF</manifestFile>
              </archive>
            </configuration>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <configuration>
            <ignoredUnusedDeclaredDependencies combine.children="append">
              <!-- dependencies wrongly detected by the plugin -->
              <!-- no occurrences in java code but deploy by Nuxeo runtime -->
              <!-- no occurrences in java code but transitive dependencies of a test-jar -->
              <artifact>org.nuxeo.ecm.automation:nuxeo-automation-core:test-jar</artifact>
              <artifact>org.nuxeo.ecm.automation:nuxeo-automation-io:test-jar</artifact>
              <artifact>org.nuxeo.ecm.automation:nuxeo-automation-server:test-jar</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-audit-test</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-collections-core:test-jar</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-filemanager:test-jar</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-test</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-webapp-types</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-search-core</artifact>
              <artifact>org.nuxeo.ecm.webengine:nuxeo-webengine-core:test-jar</artifact>
            </ignoredUnusedDeclaredDependencies>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
