
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Mon Feb 28 17:12:07 CET 2011
//----------------------------------------------------

package org.nuxeo.ecm.core.query.sql.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GROUPBY = 15;
  public static final int STARTSWITH = 39;
  public static final int GTEQ = 34;
  public static final int LPARA = 36;
  public static final int LTEQ = 33;
  public static final int DESC = 21;
  public static final int ISNOTNULL = 47;
  public static final int DOUBLE = 53;
  public static final int INTEGER = 52;
  public static final int BETWEEN = 9;
  public static final int NOTILIKE = 13;
  public static final int DATE = 41;
  public static final int ORDERBY = 14;
  public static final int WHERE = 4;
  public static final int IS = 44;
  public static final int NOT = 24;
  public static final int AND = 22;
  public static final int LT = 31;
  public static final int OFFSET = 43;
  public static final int TYPE = 40;
  public static final int IN = 6;
  public static final int OR = 23;
  public static final int LOCATION = 38;
  public static final int COMMA = 35;
  public static final int DIV = 27;
  public static final int SELECT = 2;
  public static final int RPARA = 37;
  public static final int PATH_IDENTIFIER = 50;
  public static final int EOF = 0;
  public static final int NOTLIKE = 12;
  public static final int error = 1;
  public static final int DISTINCT = 18;
  public static final int ISNULL = 46;
  public static final int MUL = 28;
  public static final int LIKE = 7;
  public static final int LIMIT = 17;
  public static final int ILIKE = 8;
  public static final int NULL = 45;
  public static final int TIMESTAMP = 42;
  public static final int NOTBETWEEN = 10;
  public static final int EQ = 29;
  public static final int FROM = 3;
  public static final int ASC = 20;
  public static final int NOTIN = 11;
  public static final int SUM = 25;
  public static final int STRING = 51;
  public static final int ALL = 19;
  public static final int AS = 5;
  public static final int GT = 32;
  public static final int SUB = 26;
  public static final int FROM_IDENTIFIER = 49;
  public static final int NOTEQ = 30;
  public static final int IDENTIFIER = 48;
  public static final int HAVING = 16;
}

