#!/bin/sh

JAVA_OPTS="$JAVA_OPTS -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n"


COREDIR=../nuxeo-webengine-gwt-core
UIDIR=../nuxeo-webengine-gwt-ui
APPDIR=`dirname $0`;
if [ "x$GWT_HOME" = "x" ] ; then
    echo GWT_HOME not defined
    exit 1;
fi
java  $JAVA_OPTS -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$COREDIR/src:$COREDIR/bin:$UIDIR/src:$UIDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/target/www" "$@" org.nuxeo.ecm.webengine.gwt.test.Main/Main.html;
