#!/bin/bash
#
# nxserverctl        Startup script for Nuxeo Web Engine
#
# chkconfig: - 85 15
# description: Starts LM Portal based on Nuxeo Web Engine
# config: /etc/sysconfig/nxportal
# pidfile: /opt/lm-portal/nuxeo.pid

PS="ps"
GREP="grep"
SERVERNAME="nxserver"
ECHO="echo"
SLEEP="sleep"
NOHUP="nohup"
AWK="awk"
TERM="kill -15"
KILL="kill -9"
DIR=/opt/lm-portal
PID_FILE="/var/run/nuxeo.pid"

[ -f /etc/sysconfig/nxportal ] && . /etc/sysconfig/nxportal
[ -f ~/etc/sysconfig/nxportal ] && . ~/etc/sysconfig/nxportal

export JAVA_HOME

DATA=${DATA-/opt/nxdata}

function print_usage {
  echo "Usage: ./nxserverctl.sh {start | stop | status | pid } {datapath}";
}


function server_pid {
  PID=""
  if [ -f $PID_FILE ]; then
     PID=`cat "$PID_FILE"`
  else
     PID=$( ${PS} aux | ${GREP} "java" | ${GREP} "nuxeo-runtime-launcher" | ${AWK} '{print $2}' )
  fi
}

function check_server {
   server_pid
   if [ "${PID}" = "" ]; then
      return 1
   else
      return 0
   fi
}


function server_status {
   check_server
   if [ "$?" -eq "0" ]; then
      server_pid
      if [ "${ACTION}" = "start" ]; then
         ${ECHO} "${SERVERNAME} has been started: ${PID}"
      else
         ${ECHO} "${SERVERNAME} is started: ${PID}"
      fi
   else
      ${ECHO} "${SERVERNAME} is stopped"
   fi
}

function stop_server {
  check_server
  if [ "$?" -eq "1" ]; then
    print_error "${SERVERNAME} is already stopped" && exit 1
  fi
  if [ -f $PID_FILE ]; then
      rm $PID_FILE
  fi
  ${TERM} ${PID}
  ${SLEEP} 5
  check_server
  if [ "$?" -eq "1" ]; then
    ${ECHO} "${SERVERNAME} has been shutdown"
  else
    ${KILL} ${PID}
    ${SLEEP} 5
    check_server
    if [ "$?" -eq "1" ]; then
      ${ECHO} "${SERVERNAME} has been killed"
    else
      ${ECHO} "Failed to shutdown server. PID: ${PID}"
    fi
  fi
}

function start_server {
  check_server
  if [ "$?" -eq "0" ]; then
    print_error "${SERVERNAME} is already started" && exit 1
  fi

  pushd ${DIR} > /dev/null
  ${NOHUP} /bin/bash ${DIR}/nxserver.sh -data $DATA > /dev/null 2>&1 &
  popd > /dev/null


  echo "$!" > $PID_FILE
  ${SLEEP} 5
  server_status
}

function print_error {
  ${ECHO} "Error: $@" >&2
}


ACTION="$1"
case ${ACTION} in
     "start")  start_server ;;
     "stop")  stop_server    ;;
     "status")  server_status ;;
     "pid") server_pid ; echo ${PID}  ;;
     *  )  print_usage && exit 1   ;;
esac

