<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
    <artifactId>nuxeo-platform-parent</artifactId>
    <version>2026.1-SNAPSHOT</version>
  </parent>

  <groupId>cloud.docbyte.nuxeo.ecm</groupId>
  <artifactId>nuxeo-drive-parent</artifactId>
  <packaging>pom</packaging>
  <name>Nuxeo Drive Parent</name>
  <description>Parent project for the Nuxeo Drive addon
  </description>

  <modules>
    <module>nuxeo-drive-core</module>
    <module>nuxeo-drive-operations</module>
    <module>nuxeo-drive-elasticsearch</module>
    <module>nuxeo-drive-rest-api</module>
    <module>nuxeo-drive-core-dependencies</module>
  </modules>

  <profiles>
    <profile>
      <id>bench</id>
      <modules>
        <module>nuxeo-drive-bench</module>
      </modules>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <configuration>
              <!-- Allows to skip surefire tests without skipping failsafe tests -->
              <skipTests>${skip.surefire.tests}</skipTests>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>
