<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.nuxeo.runtime</groupId>
    <artifactId>nuxeo-runtime-parent</artifactId>
    <version>2025.20-SNAPSHOT</version>
  </parent>

  <artifactId>nuxeo-runtime-opensearch1-embed</artifactId>
  <name>Nuxeo Runtime OpenSearch 1.x Embed</name>

  <dependencies>
    <!-- Libraries -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-base</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-codec-compression</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch.plugin</groupId>
      <artifactId>analysis-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch.plugin</groupId>
      <artifactId>transport-netty4-client</artifactId>
    </dependency>

    <!-- Nuxeo dependencies -->
    <dependency>
      <groupId>org.nuxeo.common</groupId>
      <artifactId>nuxeo-common</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime</artifactId>
    </dependency>

    <!-- Nuxeo test dependencies -->
    <dependency>
      <groupId>org.nuxeo.common</groupId>
      <artifactId>nuxeo-common-test</artifactId>
    </dependency>
    <dependency>
      <groupId>org.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-test</artifactId>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.nuxeo</groupId>
        <artifactId>nuxeo-opensearch1-bom</artifactId>
        <version>${nuxeo.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <archive>
                <manifestFile>src/test/resources/META-INF/MANIFEST.MF</manifestFile>
              </archive>
            </configuration>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
