//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.20 at 10:45:28 AM EEST 
//


package org.nuxeo.ecm.platform.tag.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.nuxeo.ecm.platform.tag.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TagserviceConfig_QNAME = new QName("http://tagservice.nuxeo.org", "tagservice-config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.nuxeo.ecm.platform.tag.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Properties }
     * 
     */
    public Properties createProperties() {
        return new Properties();
    }

    /**
     * Create an instance of {@link TagserviceConfig }
     * 
     */
    public TagserviceConfig createTagserviceConfig() {
        return new TagserviceConfig();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TagserviceConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://tagservice.nuxeo.org", name = "tagservice-config")
    public JAXBElement<TagserviceConfig> createTagserviceConfig(TagserviceConfig value) {
        return new JAXBElement<TagserviceConfig>(_TagserviceConfig_QNAME, TagserviceConfig.class, null, value);
    }

}
