//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.20 at 10:45:28 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tagservice.nuxeo.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.nuxeo.ecm.platform.tag.config;
