<html><head><title>vermeer RPC packet</title></head>
<body>
<p>method=list documents:${request.version}
<p>document_list=
<ul>
<#if listFiles>
<#list files as item>
<ul>
<li>document_name=${item.getRelativeFilePath(siteRoot)}
<li>meta_info=
<ul>
<li>Subject
<li>SW|
<li>vti_rtag
<li>SW|rt:${item.etag}@00000000004
<li>vti_etag
<li>SW|&#34;&#123;${item.etag}&#125;,3&#34;
<li>vti_parserversion
<li>SR|${config.WSSServerVersion}
<li>vti_timecreated
<li>TR|${item.createdTS}
<li>vti_title
<li>SW|${item.title}
<li>_Author
<li>SW|Tiry
<li>_Category
<li>EW|
<li>ContentType
<li>EW|folder
<li>ContentTypeId
<li>SW|0x010100EF2F1ABABCCD3940B03ADFD2A092ED04
<li>vti_timelastmodified
<li>TR|${item.modifiedTS}
<li>vti_nexttolasttimemodified
<li>TR|${item.modifiedTS}
<li>vti_sourcecontrolmultiuserchkoutby
<li>VR|${request.userName}
<li>vti_canmaybeedit
<li>BX|true
<li>vti_candeleteversion
<li>BR|true
<li>_Comments
<li>SW|
<li>vti_author
<li>SR|${request.userName}
<li>vti_sourcecontrolcheckedoutby
<li>SR|${request.userName}
<li>vti_sourcecontroltimecheckedout
<li>TR|${item.checkoutTS}
<li>vti_sourcecontrolversion
<li>SR|V2.0
<li>vti_sourcecontrolcookie
<li>SR|fp_internal
<li>vti_level
<li>IR|255
<li>Keywords
<li>SW|
<li>_Status
<li>EW|
<li>vti_modifiedby
<li>SR|${request.userName}
<li>vti_filesize
<li>IR|${item.size}
</ul>
</ul>
</#list>
</#if>
</ul>
<p>urldirs=
<ul>
<ul>
<li>url=${parent.getRelativeFilePath(siteRoot)}
<li>meta_info=
<ul>
<li>vti_isexecutable
<li>BR|false
<li>vti_level
<li>IR|1
<li>vti_rtag
<li>SW|rt:${parent.etag}@00000000004
<li>vti_etag
<li>SW|&#34;&#123;${parent.etag}&#125;,0&#34;
<li>vti_isbrowsable
<li>BR|true
<li>vti_isscriptable
<li>BR|false
<li>vti_hassubdirs
<li>BR|true
<li>vti_timecreated
<li>TR|${parent.createdTS}
<li>vti_candeleteversion
<li>BR|true
<li>vti_dirlateststamp
<li>TW|${parent.modifiedTS}
<li>vti_timelastmodified
<li>TR|${parent.modifiedTS}
<li>vti_listname
<li>SR|&#123;${parent.etag}&#125;
<li>vti_listtitle
<li>SR|${parent.name}
<li>vti_listbasetype
<li>IR|1
<li>vti_listenableversioning
<li>BR|false
<li>vti_listrequirecheckout
<li>BR|false
</ul>
</ul>
<#if listFolders>
<#list folders as item>
<ul>
<li>url=${item.getRelativeFilePath(siteRoot)}
<li>meta_info=
<ul>
<li>vti_isexecutable
<li>BR|false
<li>vti_level
<li>IR|1
<li>vti_rtag
<li>SW|rt:${item.etag}@00000000004
<li>vti_etag
<li>SW|&#34;&#123;${item.etag}&#125;,0&#34;
<li>vti_isbrowsable
<li>BR|true
<li>vti_isscriptable
<li>BR|false
<li>vti_hassubdirs
<li>BR|true
<li>vti_timecreated
<li>TR|${item.createdTS}
<li>vti_candeleteversion
<li>BR|true
<li>vti_dirlateststamp
<li>TW|${item.modifiedTS}
<li>vti_timelastmodified
<li>TR|${item.modifiedTS}
</ul>
</ul>
</#list>
</#if>
</ul>
</body>
</html>
