<html><head><title>vermeer RPC packet</title></head>
<body>
<p>method=move document:${request.version}
<p>message=successfully renamed URL '${oldUrl}' as '${newUrl}'
<p>oldUrl=${oldUrl}
<p>newUrl=${newUrl}
<p>document_list=
<ul>
</ul>
<p>moved_docs=
<ul>
<ul>
<li>document_name=${newUrl}
<li>meta_info=
<ul>
<li>Subject
<li>SW|
<li>vti_rtag
<li>SW|rt:${doc.etag}@00000000002
<li>vti_etag
<li>SW|&#34;&#123;${doc.etag}&#125;,2&#34;
<li>vti_hasdefaultcontent
<li>BX|true
<li>vti_error0
<li>SX|Could not process the file wdtmpl.doc as a Microsoft Office document.
<li>vti_parserversion
<li>SR|${config.WSSServerVersion}
<li>vti_timecreated
<li>TR|${doc.createdTS}
<li>vti_title
<li>SR|
<li>_Author
<li>SW|
<li>_Category
<li>SW|
<li>vti_timelastmodified
<li>TR|${doc.modifiedTS}
<li>vti_nexttolasttimemodified
<li>TR|${doc.modifiedTS}
<li>vti_candeleteversion
<li>BR|true
<li>_Comments
<li>SW|
<li>vti_linkinfo
<li>VX|
<li>vti_author
<li>SR|
<li>vti_setuppath
<li>SX|1033&#92;STS&#92;doctemp&#92;word&#92;wdtmpl.doc
<li>vti_sourcecontrolversion
<li>SR|V1.0
<li>vti_sourcecontrolcookie
<li>SR|fp_internal
<li>vti_level
<li>IR|1
<li>vti_filesize
<li>IR|{doc.size}
<li>Keywords
<li>SW|
<li>vti_modifiedby
<li>SR|
</ul>
</ul>
</ul>
<p>moved_dirs=
<ul>
</ul>
</body>
</html>