<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>cloud.docbyte.nuxeo.ecm</groupId>
    <artifactId>nuxeo-drive-parent</artifactId>
    <version>2026.1-SNAPSHOT</version>
  </parent>

  <artifactId>nuxeo-drive-core</artifactId>
  <name>Nuxeo Drive Core</name>
  <description>Core types for Nuxeo Drive</description>

  <dependencies>
    <!-- Java specifications -->

    <!-- Libraries -->
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>

    <!-- Nuxeo dependencies -->
    <dependency>
      <groupId>cloud.docbyte.nuxeo.lib.stream</groupId>
      <artifactId>nuxeo-stream</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-stream</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-api</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-bulk</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-event</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-io</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-query</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-schema</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-audit-core</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-collections-core</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-filemanager</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-notification</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-query-api</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-usermanager</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-userworkspace</artifactId>
    </dependency>

    <!-- Test libraries -->
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Nuxeo test libraries -->
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-jtajca</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.core</groupId>
      <artifactId>nuxeo-core-cache</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.automation</groupId>
      <artifactId>nuxeo-automation-core</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-audit-test</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-collections-core</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-directory-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-dublincore</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-filemanager</artifactId>
      <type>test-jar</type>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>-->
<!--      <artifactId>nuxeo-platform-login-token</artifactId>-->
<!--      <scope>provided</scope>-->
<!--    </dependency>-->
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-tag</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-test</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-platform-webapp-types</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.ecm.platform</groupId>
      <artifactId>nuxeo-search-core</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <archive>
                <manifestFile>
                  src/test/resources/META-INF/MANIFEST.MF
                </manifestFile>
              </archive>
            </configuration>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <configuration>
            <ignoredUnusedDeclaredDependencies combine.children="append">
              <!-- dependencies wrongly detected by the plugin -->
              <!-- no occurrences in java code but deploy by Nuxeo runtime -->
              <artifact>org.nuxeo.ecm.automation:nuxeo-automation-core</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-directory-api</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-tag</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-platform-webapp-types</artifact>
              <artifact>org.nuxeo.ecm.platform:nuxeo-search-core</artifact>
              <!-- no occurrences in java code but transitive dependencies of a test-jar -->
              <artifact>org.nuxeo.ecm.automation:nuxeo-automation-core</artifact>
            </ignoredUnusedDeclaredDependencies>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
