nuxeo:
  enable: false
redis:
  master:
    podLabels:
      branch: "$BRANCH_NAME"
      resource: pod
      team: platform
      usage: utests
    service:
      labels:
        branch: "$BRANCH_NAME"
        resource: service
        team: platform
        usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
tags:
  redis: true
