kafka:
  podLabels:
    branch: "$BRANCH_NAME"
    resource: pod
    team: platform
    usage: utests
  tolerations:
    - key: team
      operator: Equal
      value: platform
      effect: NoSchedule
  nodeSelector:
    team: platform
  configurationOverrides:
    auto.create.topics.enable: false
    group.initial.rebalance.delay.ms: 100
    log.retention.minutes: 20
    offsets.retention.minutes: 20
    offsets.topic.num.partitions: 5
    transaction.state.log.min.isr: 1
    transaction.state.log.replication.factor: 1
  zookeeper:
    podLabels:
      branch: "$BRANCH_NAME"
      resource: pod
      team: platform
      usage: utests
    tolerations:
      - key: team
        operator: Equal
        value: platform
        effect: NoSchedule
    nodeSelector:
      team: platform
tags:
  kafka: true
