
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Tue Dec 15 12:16:13 CET 2009
//----------------------------------------------------

package org.nuxeo.ecm.core.query.sql.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int GROUPBY = 14;
  public static final int STARTSWITH = 38;
  public static final int GTEQ = 33;
  public static final int LPARA = 35;
  public static final int LTEQ = 32;
  public static final int DESC = 20;
  public static final int DOUBLE = 48;
  public static final int INTEGER = 47;
  public static final int BETWEEN = 9;
  public static final int DATE = 40;
  public static final int ORDERBY = 13;
  public static final int WHERE = 4;
  public static final int NOT = 23;
  public static final int AND = 21;
  public static final int LT = 30;
  public static final int OFFSET = 42;
  public static final int TYPE = 39;
  public static final int IN = 6;
  public static final int OR = 22;
  public static final int LOCATION = 37;
  public static final int COMMA = 34;
  public static final int DIV = 26;
  public static final int SELECT = 2;
  public static final int RPARA = 36;
  public static final int PATH_IDENTIFIER = 45;
  public static final int EOF = 0;
  public static final int NOTLIKE = 12;
  public static final int error = 1;
  public static final int DISTINCT = 17;
  public static final int MUL = 27;
  public static final int LIKE = 7;
  public static final int LIMIT = 16;
  public static final int ILIKE = 8;
  public static final int TIMESTAMP = 41;
  public static final int NOTBETWEEN = 10;
  public static final int EQ = 28;
  public static final int FROM = 3;
  public static final int ASC = 19;
  public static final int NOTIN = 11;
  public static final int SUM = 24;
  public static final int STRING = 46;
  public static final int ALL = 18;
  public static final int AS = 5;
  public static final int GT = 31;
  public static final int SUB = 25;
  public static final int FROM_IDENTIFIER = 44;
  public static final int NOTEQ = 29;
  public static final int IDENTIFIER = 43;
  public static final int HAVING = 15;
}

