<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cloud.docbyte.nuxeo.runtime</groupId>
    <artifactId>nuxeo-runtime-parent</artifactId>
    <version>2026.1-SNAPSHOT</version>
  </parent>

  <artifactId>nuxeo-runtime-opensearch1</artifactId>
  <name>Nuxeo Runtime OpenSearch 1.x</name>

  <dependencies>
    <!-- Libraries -->
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>
    <dependency>
      <groupId>net.jodah</groupId>
      <artifactId>failsafe</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpasyncclient</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opencensus</groupId>
      <artifactId>opencensus-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-x-content</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch.client</groupId>
      <artifactId>opensearch-rest-client</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch.client</groupId>
      <artifactId>opensearch-rest-high-level-client</artifactId>
    </dependency>

    <!-- Nuxeo dependencies -->
    <dependency>
      <groupId>cloud.docbyte.nuxeo.common</groupId>
      <artifactId>nuxeo-common</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-launcher-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-opensearch1-embed</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- Test libraries -->
    <dependency>
      <groupId>jakarta.inject</groupId>
      <artifactId>jakarta.inject-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>signer</artifactId>
    </dependency>

    <!-- Nuxeo test dependencies -->
    <dependency>
      <groupId>cloud.docbyte.nuxeo.common</groupId>
      <artifactId>nuxeo-common-test</artifactId>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-opensearch1-embed</artifactId>
      <type>test-jar</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.runtime</groupId>
      <artifactId>nuxeo-runtime-test</artifactId>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>cloud.docbyte.nuxeo</groupId>
        <artifactId>nuxeo-opensearch1-bom</artifactId>
        <version>${nuxeo.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <archive>
                <manifestFile>src/test/resources/META-INF/MANIFEST.MF</manifestFile>
              </archive>
            </configuration>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <configuration>
            <ignoredUnusedDeclaredDependencies combine.children="append">
              <!-- dependencies wrongly detected by the plugin -->
              <!-- no occurrences in java code but deploy by Nuxeo runtime -->
              <artifact>org.nuxeo.runtime:nuxeo-runtime-opensearch1-embed</artifact>
              <!-- no occurrences in java code but transitive dependencies of a test-jar -->
            </ignoredUnusedDeclaredDependencies>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
