
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

nuxeo:
  nuxeo:
    image: 
      repository:  
      tag: 
      pullPolicy: IfNotPresent
  mongodb:
    deploy: false 
  postgresql:
    deploy: false
