#!/bin/sh
COREDIR=../nuxeo-webengine-gwt-core
if [ "x$GWT_HOME" = "x" ] ; then
    echo GWT_HOME not defined
    exit 1;
fi
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$COREDIR/src:$COREDIR/bin:$GWT_HOME/gwt-user.jar:$GWT_HOME/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/target/www" "$@" org.nuxeo.ecm.webengine.gwt.UI;
