nuxeo:
  enabled: false
mongodb:
  enabled: true
postgresql:
  enabled: false
opensearch:
  enabled: true
kafka:
  enabled: true

# values definition
global:
  labels:
    dev.nuxeo.com/usage: utests
