nuxeo.test.s3storage.bucket=nuxeo-platform-unit-tests-us-east
nuxeo.test.s3storage.transient.bucket=nuxeo-platform-unit-tests-transient-us-east
nuxeo.test.s3storage.bucket_prefix=$BUCKET_PREFIX
nuxeo.test.s3storage.provider.test.bucket_prefix=$TEST_BLOB_PROVIDER_PREFIX
nuxeo.test.s3storage.provider.other.bucket_prefix=$OTHER_BLOB_PROVIDER_PREFIX
nuxeo.test.s3storage.crypt.kms.clientside.key=4af4d8ff-94bd-470d-8ce3-bdd117adf86a
nuxeo.test.s3storage.crypt.kms.key=4af4d8ff-94bd-470d-8ce3-bdd117adf86a
