/*
 * (C) Copyright 2018 Nuxeo (http://nuxeo.com/) and others.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *     Funsho David
 *     Nuno Cunha <ncunha@nuxeo.com>
 */

package org.nuxeo.ecm.platform.comment.api;

import java.util.List;

import org.nuxeo.ecm.core.api.CoreSession;
import org.nuxeo.ecm.platform.comment.api.exceptions.CommentNotFoundException;

/**
 * Annotation API to perform CRUD operations on annotations.
 *
 * @since 10.1
 */
public interface AnnotationService {

    /**
     * Creates an annotation on a document.
     *
     * @param session the core session
     * @param annotation the annotation to create
     * @return the created annotation
     */
    Annotation createAnnotation(CoreSession session, Annotation annotation);

    /**
     * Gets an annotation.
     *
     * @param session the core session
     * @param annotationId the annotation document model id
     * @throws CommentNotFoundException if no annotation was found with the given id
     * @return the annotation, or {@code null} if the annotation with the given id was not found
     */
    Annotation getAnnotation(CoreSession session, String annotationId) throws CommentNotFoundException;

    /**
     * Gets all annotations for a document.
     *
     * @param session the core session
     * @param documentId the annotated document id
     * @param xpath the annotated blob xpath in the document
     * @throws CommentNotFoundException if no annotation was found with the given id
     * @return the list of annotations, or an empty list if no annotation is found
     */
    List<Annotation> getAnnotations(CoreSession session, String documentId, String xpath)
            throws CommentNotFoundException;

    /**
     * Updates an annotation for a document.
     *
     * @param session the core session
     * @param annotationId the annotation document model id
     * @param annotation the annotation containing the modifications
     * @throws CommentNotFoundException if no annotation was found with the given id
     */
    void updateAnnotation(CoreSession session, String annotationId, Annotation annotation)
            throws CommentNotFoundException;

    /**
     * Deletes an annotation for a document.
     *
     * @param session the core session
     * @param annotationId the annotation document model id
     * @throws CommentNotFoundException if no annotation was found with the given id
     */
    void deleteAnnotation(CoreSession session, String annotationId) throws CommentNotFoundException;

    /**
     * Gets an annotation generated by an external service.
     *
     * @param session the core session
     * @param entityId the annotation entity id
     * @return the annotation
     * @throws CommentNotFoundException if no annotation was found with the given external entity id
     * @since 10.3
     */
    Annotation getExternalAnnotation(CoreSession session, String entityId) throws CommentNotFoundException;

    /**
     * Updates an external annotation.
     *
     * @param session the core session
     * @param entityId the annotation document model id
     * @param annotation the annotation containing the modifications
     * @throws CommentNotFoundException if no annotation was found with the given external entity id
     * @since 10.3
     */
    void updateExternalAnnotation(CoreSession session, String entityId, Annotation annotation)
            throws CommentNotFoundException;

    /**
     * Deletes an external annotation.
     *
     * @param session the core session
     * @param entityId the annotation entity id
     * @throws CommentNotFoundException if no annotation was found with the given external entity id
     * @since 10.3
     */
    void deleteExternalAnnotation(CoreSession session, String entityId) throws CommentNotFoundException;

}
