<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>cloud.docbyte.nuxeo.docker</groupId>
    <artifactId>nuxeo-docker-images</artifactId>
    <version>2026.1-SNAPSHOT</version>
  </parent>

  <artifactId>nuxeo-benchmark-docker-image</artifactId>
  <name>Nuxeo Benchmark Docker Image</name>
  <packaging>pom</packaging>

  <properties>
    <docker.base.image>nuxeo/nuxeo:2025.x</docker.base.image>
  </properties>

  <dependencies>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.packages</groupId>
      <artifactId>nuxeo-amazon-s3-package</artifactId>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.packages</groupId>
      <artifactId>nuxeo-audit-opensearch1-package</artifactId>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.packages</groupId>
      <artifactId>nuxeo-importer-package</artifactId>
      <type>zip</type>
    </dependency>
    <dependency>
      <groupId>cloud.docbyte.nuxeo.packages</groupId>
      <artifactId>nuxeo-search-client-opensearch1-package</artifactId>
      <type>zip</type>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-packages</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <includeGroupIds>cloud.docbyte.nuxeo.packages</includeGroupIds>
              <outputDirectory>${project.build.directory}/packages</outputDirectory>
              <overWriteIfNewer>true</overWriteIfNewer>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>tag</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <images>
            <image>
              <name>nuxeo/nuxeo-benchmark:2025.x</name>
              <build>
                <args>
                  <BASE_IMAGE>${docker.base.image}</BASE_IMAGE>
                  <BUILD_TAG>local-nuxeo-nuxeo-benchmark</BUILD_TAG>
                  <SCM_REF>local</SCM_REF>
                  <VERSION>2025.x</VERSION>
                  <BUILD_DIR>target-${custom.environment}</BUILD_DIR>
                </args>
                <contextDir>${basedir}</contextDir>
                <buildx>
                  <platforms>
                    <platform>${docker.platforms}</platform>
                  </platforms>
                </buildx>
              </build>
            </image>
          </images>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
