name: Bot Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: nuxeo/gh-build-tools/.github/workflows/bot-auto-merge.yml@80f0c5b954b417cf698f2a2201f6ac7dfeb2adca # v0.10.3
