name: Bot Auto Merge
on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'nuxeo-platform-jx-bot'
    steps:
      - name: Print workflow information
        run:
          echo Author = ${{ github.actor }}
      - name: Dependabot metadata
        id: metadata
        if: github.actor == 'dependabot[bot]'
        uses: dependabot/fetch-metadata@v1.3.5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve bot PRs
        if: |
          github.actor == 'nuxeo-platform-jx-bot'
          || steps.metadata.outputs.update-type == 'version-update:semver-minor'
          || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for bot PRs
        if: |
          github.actor == 'nuxeo-platform-jx-bot'
          || steps.metadata.outputs.update-type == 'version-update:semver-minor'
          || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
