name: Bot Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: nuxeo/gh-build-tools/.github/workflows/bot-auto-merge.yml@cb16f4998b4ce5e14338211c73ea909fa5a6c219 # v0.10.2
