name: Bot Auto Merge

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: nuxeo/gh-build-tools/.github/workflows/bot-auto-merge.yml@0b99a8caf7f0173315ce88afe9255798b1a14746 # v0.12.2
