name: "Dependency Graph Submission"

on:
  push:
    branches: [ "2023" ]
  pull_request:
    branches: [ "2023" ]

env:
  MAVEN_OPTS: -Xms6g -Xmx6g -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  MAVEN_ARGS: -B -V -nsu -Dnuxeo.skip.enforcer=true -DskipTests

jobs:
  analyze-deps:
    name: Generate and submit dependency graph
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'maven'

    # Build to populate the target directories with the complete list of JAR files of the dependency tree, including transitive dependencies
    # E.g.:
    # - packages/nuxeo-amazon-s3-package/target/nuxeo-amazon-s3-package-*.zip:install/lib/aws-java-sdk-kms-*.jar
    # - server/nuxeo-server-tomcat/target/nuxeo-server-tomcat-*.zip:nuxeo-server-tomcat-*/nxserver/lib/HdrHistogram-*.jar
    - name: Build modules
      run: |
        mvn ${{ env.MAVEN_ARGS }} -T4C install

    - name: Build server
      run: |
        mvn ${{ env.MAVEN_ARGS }} -f server/pom.xml install

    - name: Build packages
      run: |
        mvn ${{ env.MAVEN_ARGS }} -f packages/pom.xml install

    - name: Build functional tests
      run: |
        mvn ${{ env.MAVEN_ARGS }} -f ftests/pom.xml install

    - name: Submit dependency graph
      uses: anchore/sbom-action@v0
      with:
        dependency-snapshot: true
