name: "Docker image scan"

on:
  # Run manually or with the GitHub CLI
  workflow_dispatch:
    inputs:
      internalRegistry:
        description: 'Use internal Docker registry'
        type: boolean
      imageName:
        description: 'Docker image name'
        required: true
        default: 'nuxeo/nuxeo:2023.x'
        type: string

env:
  DOCKER_REGISTRY: ${{ inputs.internalRegistry && vars.DOCKER_REGISTRY_INTERNAL || vars.DOCKER_REGISTRY_PRIVATE }}
  DOCKER_REGISTRY_USERNAME: ${{ inputs.internalRegistry && secrets.INTERNAL_REPOSITORY_MANAGER_USERNAME || secrets.REPOSITORY_MANAGER_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ inputs.internalRegistry && secrets.INTERNAL_REPOSITORY_MANAGER_PASSWORD || secrets.REPOSITORY_MANAGER_PASSWORD }}

jobs:
  scan:
    name: Scan Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Print workflow inputs
        run: |
          echo internalRegistry = ${{ inputs.internalRegistry }}
          echo imageName = ${{ inputs.imageName }}

      - name: Log in to Docker registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}

      - name: Scan Docker image with Grype - console output
        uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium
          output-format: table

      - name: Scan Docker image with Grype - JSON output
        if: always() # necessary as using a failure threshold in the scan step
        id: scan-json
        uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium
          output-format: json

      - name: Print Grype JSON output
        if: always() # necessary as using a failure threshold in the scan step
        run:
          cat ${{ steps.scan-json.outputs.json }} | jq

      - name: Scan Docker image with Grype - SARIF output
        if: always() # necessary as using a failure threshold in the scan step
        id: scan-sarif
        uses: anchore/scan-action@f6601287cdb1efc985d6b765bbf99cb4c0ac29d8 # v7.0.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium

      - name: Upload SARIF file
        if: always() # necessary as using a failure threshold in the scan step
        uses: github/codeql-action/upload-sarif@f443b600d91635bebf5b0d9ebc620189c0d6fba5 # v4.30.8
        with:
          sarif_file: ${{ steps.scan-sarif.outputs.sarif }}
