name: "Docker image scan"

on:
  # Run manually or with the GitHub CLI
  workflow_dispatch:
    inputs:
      internalRegistry:
        description: 'Use internal Docker registry'
        type: boolean
      imageName:
        description: 'Docker image name'
        required: true
        default: 'nuxeo/nuxeo:2023.x'
        type: string

env:
  DOCKER_REGISTRY: ${{ inputs.internalRegistry && vars.DOCKER_REGISTRY_INTERNAL || vars.DOCKER_REGISTRY_PRIVATE }}
  DOCKER_REGISTRY_USERNAME: ${{ inputs.internalRegistry && secrets.INTERNAL_REPOSITORY_MANAGER_USERNAME || secrets.REPOSITORY_MANAGER_USERNAME }}
  DOCKER_REGISTRY_PASSWORD: ${{ inputs.internalRegistry && secrets.INTERNAL_REPOSITORY_MANAGER_PASSWORD || secrets.REPOSITORY_MANAGER_PASSWORD }}

jobs:
  scan:
    name: Scan Docker image
    runs-on: ubuntu-latest

    steps:
      # Required to read vex.json configuration
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Print workflow inputs
        run: |
          echo internalRegistry = ${{ inputs.internalRegistry }}
          echo imageName = ${{ inputs.imageName }}

      - name: Log in to Docker registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_REGISTRY_USERNAME }}
          password: ${{ env.DOCKER_REGISTRY_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}

      - name: Scan Docker image with Grype - console output
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium
          output-format: table
          vex: docker/vex.json

      - name: Scan Docker image with Grype - JSON output
        if: always() # necessary as using a failure threshold in the scan step
        id: scan-json
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium
          output-format: json
          vex: docker/vex.json

      - name: Print Grype JSON output
        if: always() # necessary as using a failure threshold in the scan step
        run:
          cat ${{ steps.scan-json.outputs.json }} | jq

      - name: Scan Docker image with Grype - SARIF output
        if: always() # necessary as using a failure threshold in the scan step
        id: scan-sarif
        uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
        with:
          image: ${{ env.DOCKER_REGISTRY }}/${{ inputs.imageName }}
          severity-cutoff: medium
          vex: docker/vex.json

      - name: Upload SARIF file
        if: always() # necessary as using a failure threshold in the scan step
        uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463 # v4.36.1
        with:
          sarif_file: ${{ steps.scan-sarif.outputs.sarif }}
