apiVersion: v1
kind: Service
metadata:
  name: javadoc
  labels:
    app: javadoc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
{{- with .Values.javadoc.service.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.javadoc.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.javadoc.service.type }}
  ports:
    - port: {{ .Values.javadoc.service.externalPort }}
      targetPort: {{ .Values.javadoc.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: javadoc
    release: {{ .Release.Name }}
