
DIR:=/home/madarche/mnt/arbaazob/java/jboss-4.0.5.GA-nuxeo-5.1/server/default/deploy/nuxeo.ear/plugins

deploy:
	cp /home/madarche/.m2/repository/org/nuxeo/ecm/platform/nuxeo-platform-login-cleartrust/5.1.6-SNAPSHOT/nuxeo-platform-login-cleartrust-5.1.6-SNAPSHOT.jar ${DIR}
